title: "Cards"
description: |
  Cards are to be used a either the mav navigation on the homepage.

patterns:
  nav-card:
    title: "Navigation Card"
    descripton: |
      The nav card will be used as the main navigation to go in between pages. It will be on every single page.
