title: "Navigation"
descripton: |
  Navigations are to switch through different pages in the website.

patterns:
  web-nav:
    title: "Web Navigation"
    descripton: |
      This navigation should only be used as a side navigation to show different projects on the same page. This will be used on the web page.
  print-nav:
    title: "Print Navigation"
    descripton: |
      This navigation should only be used as a side navigation to show different projects on the same page. This will be used on the print page.
  motion-nav:
    title: "Motion Navigation"
    descripton: |
      This navigation should only be used as a side navigation to show different projects on the same page. This will be used on the motion page.
